### ISSUE TITLE
Group entries by major/minor/patch in CHANGELOG output

### ISSUE THREAD

**Issue by timleslie** [Noviny/changesets#14]
My CHANGELOG output currently looks like this:

========

## 3.0.0

- [patch][b4dcf44b](https://github.com/keystonejs/keystone-5/commit/b4dcf44b):

  - Use named exports from @keystone-alpha/keystone package.

- [patch][b69fb9b7](https://github.com/keystonejs/keystone-5/commit/b69fb9b7):

  - Update dev devependencies

- [patch][baff3c89](https://github.com/keystonejs/keystone-5/commit/baff3c89):

  - Use the updated logger API

- [patch][302930a4](https://github.com/keystonejs/keystone-5/commit/302930a4):

  - Minor internal code cleanups

- [major][656e90c2](https://github.com/keystonejs/keystone-5/commit/656e90c2):

  - `WebServer.start()` no longer takes any arguments. Developer must now explicitly call `keystone.connect()` before calling `WebServer.start()`.

- [major][b4dcf44b](https://github.com/keystonejs/keystone-5/commit/b4dcf44b):

  - Make all parts of the API available as named exports.

=====

I would like this to look like this:

=====

### Major
- [656e90c2](https://github.com/keystonejs/keystone-5/commit/656e90c2): `WebServer.start()` no longer takes any arguments. Developer must now explicitly call `keystone.connect()` before calling `WebServer.start()`.
- [b4dcf44b](https://github.com/keystonejs/keystone-5/commit/b4dcf44b): Make all parts of the API available as named exports.

### Patch
- [b4dcf44b](https://github.com/keystonejs/keystone-5/commit/b4dcf44b): Use named exports from @keystone-alpha/keystone package.
- [b69fb9b7](https://github.com/keystonejs/keystone-5/commit/b69fb9b7): Update dev devependencies
- [baff3c89](https://github.com/keystonejs/keystone-5/commit/baff3c89): Use the updated logger API
- [302930a4](https://github.com/keystonejs/keystone-5/commit/302930a4): Minor internal code cleanups

===

At the moment I can update the formatting of the individual lines with `getReleaseLine`, but I can't control the overall shape of the template.

**Comment by Noviny** [comment]
Released as of `@changesets/cli 1.0.1`
