### ISSUE TITLE
Maybe rename initialize command to init

### ISSUE THREAD

**Issue by mitchellhamilton** [Noviny/changesets#15]
I was setting up build-releases on a new project (https://github.com/unstyled-components/design-system) and my gut reaction was to run `build-releases init`(I also feel like it's more standard across the ecosystem, e.g. `npm init`, `preconstruct init`, `git init`, `flow init`) but that didn't work because the command is `initialize`. This wasn't really a very big thing since build-releases logged the commands that do work which said `initialize` and I ran that and everything worked perfectly but this might be a nice little thing that could change for the rewrite or maybe I'm wrong and `initialize` is better than `init` ¯\\\_(ツ)_/¯

Also, `init` is nice because it sidesteps the `initialize` vs `initialise` problem.

**Comment by Noviny** [comment]
Superseded by #16
