### ISSUE TITLE
Add strict mode?

### ISSUE THREAD

**Issue by Noviny** [Noviny/changesets#36]
Just thinking out loud - nobody has asked for the feature yet.

Currently we only update dependencies when they leave semver, but theoretically your versioning strategy could involve releasing whenever any mono-repo-included dependencies change.

What would that look like? Is it a terrible idea? Should we support it?

**Comment by mitchellhamilton** [comment]
Couldn't people achieve the same behavior by depending on mono-repo-included dependencies without a `^` and they would get that behavior?

Or is there a case where people would want their deps to be a semver range but still release everything?

**Comment by Noviny** [comment]
>  is there a case where people would want their deps to be a semver range but still release everything?

This one. I don't know of a use-case, so probably going to say 'no, not looking at this until someone brings me a use-case', but want it to exist in the periphery of my mind.
